# Uncomment the next line to define a global platform for your project
 platform :ios, '14.4'

target 'fitnessApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for fitnessApp
  pod 'GoogleSignIn'

  target 'fitnessAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

 
  pod 'Firebase/Core', :inhibit_warnings => true
  pod 'Firebase/Database', :inhibit_warnings => true
  pod 'Firebase/Auth', :inhibit_warnings => true


  target 'fitnessAppUITests' do
    # Pods for testing
  end

end
